import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Shared/Navbar";
import Banner from "./Components/Banner";
import PopularApps from "./Components/PopularApps";
import Footer from "./Components/Footer";
import AppProvider from "@/Context/AppProvider";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Appify -Explore Apps",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AppProvider>
          <Navbar />

          <div className="bg-purple-200">
            {children}
          </div>
          <Footer />
          <ToastContainer />
        </AppProvider>

      </body>
    </html>
  );
}
